#!/usr/bin/env bash

# abcdeabcdeabc
# abcdedabcdeab
# abcdecdabcdea
# abcdebacdeabc
# abcdeadbcdeab
# abcdedcabcdea
# abcdebcdabcde
# abcdecabdeabc
# abcdebdacdeab
# abcdecbdabcde
# abcdeacbdeabc
# abcdedbacdeab
# abcdeacdbcdea
# abcdedbcabcde
# abcdebcadeabc
# abcdecadbcdea
# abcdebdcabcde
# abcdecbadeabc
# abcdeabdcdeab
# abcdedacbcdea
# abcdecdbabcde
# abcdebadcdeab
# abcdeadcbcdea
# abcdedcbabcde
# abcdeabcdceab
# abcdedabcbdea
# abcdecdabacde
# abcdebacdceab
# abcdeadbcbdea
# abcdedcabacde
# abcdeabcedabc
# abcdebcdaebcd
# abcdecabdceab
# abcdebdacbdea
# abcdebacedabc
# abcdecbdaebcd
# abcdeacbdceab
# abcdedbacbdea
# abcdeacdbacde
# abcdecabedabc
# abcdedbcaebcd
# abcdebcadceab
# abcdecadbacde
# abcdeacbedabc
# abcdebdcaebcd
# abcdecbadceab
# abcdeabdcbdea
# abcdedacbacde
# abcdebcaedabc
# abcdecdbaebcd
# abcdebadcbdea
# abcdeadcbacde
# abcdecbaedabc
# abcdedcbaebcd
# abcdeabcdbcea
# abcdedabcabde
# abcdecdabeacd
# abcdebacdbcea
# abcdeadbcabde
# abcdedcabeacd
# abcdebcdadebc
# abcdecabdbcea
# abcdebdacabde
# abcdecbdadebc
# abcdeacbdbcea
# abcdedbacabde
# abcdeacdbeacd
# abcdedbcadebc
# abcdebcadbcea
# abcdecadbeacd
# abcdebdcadebc
# abcdecbadbcea
# abcdeabdcabde
# abcdedacbeacd
# abcdecdbadebc
# abcdebadcabde
# abcdeadcbeacd
# abcdedcbadebc
# abcdeabcdaebc
# abcdedabcedab
# abcdecdabdcea
# abcdebacdaebc
# abcdeadbcedab
# abcdedcabdcea
# abcdebcdacbde
# abcdecabdaebc
# abcdebdacedab
# abcdecbdacbde
# abcdeacbdaebc
# abcdedbacedab
# abcdeacdbdcea
# abcdedbcacbde
# abcdebcadaebc
# abcdecadbdcea
# abcdebdcacbde
# abcdecbadaebc
# abcdeabdcedab
# abcdedacbdcea
# abcdecdbacbde
# abcdebadcedab
# abcdeadcbdcea
# abcdedcbacbde
# abcdeabcdecab
# abcdedabcdbea
# abcdecdabcade
# abcdebacdecab
# abcdeadbcdbea
# abcdedcabcade
# abcdebcdabecd
# abcdecabdecab
# abcdebdacdbea
# abcdecbdabecd
# abcdeacbdecab
# abcdedbacdbea
# abcdeacdbcade
# abcdedbcabecd
# abcdebcadecab
# abcdecadbcade
# abcdebdcabecd
# abcdecbadecab
# abcdeabdcdbea
# abcdedacbcade
# abcdecdbabecd
# abcdebadcdbea
# abcdeadcbcade
# abcdedcbabecd
# abcdeabcdcbea
# abcdedabcbade
# abcdecdabaecd
# abcdebacdcbea
# abcdeadbcbade
# abcdedcabaecd
# abcdeabcedcab
# abcdebcdaedbc
# abcdecabdcbea
# abcdebdacbade
# abcdebacedcab
# abcdecbdaedbc
# abcdeacbdcbea
# abcdedbacbade
# abcdeacdbaecd
# abcdecabedcab
# abcdedbcaedbc
# abcdebcadcbea
# abcdecadbaecd
# abcdeacbedcab
# abcdebdcaedbc
# abcdecbadcbea
# abcdeabdcbade
# abcdedacbaecd
# abcdebcaedcab
# abcdecdbaedbc
# abcdebadcbade
# abcdeadcbaecd
# abcdecbaedcab
# abcdedcbaedbc
# abcdeabcdabce
# abcdedabceabd
# abcdecdabdeac
# abcdebacdabce
# abcdeadbceabd
# abcdedcabdeac
# abcdebcdacdeb
# abcdecabdabce
# abcdebdaceabd
# abcdecbdacdeb
# abcdeacbdabce
# abcdedbaceabd
# abcdeacdbdeac
# abcdedbcacdeb
# abcdebcadabce
# abcdecadbdeac
# abcdebdcacdeb
# abcdecbadabce
# abcdeabdceabd
# abcdedacbdeac
# abcdecdbacdeb
# abcdebadceabd
# abcdeadcbdeac
# abcdedcbacdeb
# abcdeabcdbeac
# abcdedabcadeb
# abcdecdabecda
# abcdebacdbeac
# abcdeadbcadeb
# abcdedcabecda
# abcdebcdadbce
# abcdecabdbeac
# abcdebdacadeb
# abcdecbdadbce
# abcdeacbdbeac
# abcdedbacadeb
# abcdeacdbecda
# abcdedbcadbce
# abcdebcadbeac
# abcdecadbecda
# abcdebdcadbce
# abcdecbadbeac
# abcdeabdcadeb
# abcdedacbecda
# abcdecdbadbce
# abcdebadcadeb
# abcdeadcbecda
# abcdedcbadbce
# abcdeabcdaceb
# abcdedabcebda
# abcdecdabdace
# abcdebacdaceb
# abcdeadbcebda
# abcdedcabdace
# abcdebcdacebd
# abcdecabdaceb
# abcdebdacebda
# abcdecbdacebd
# abcdeacbdaceb
# abcdedbacebda
# abcdeacdbdace
# abcdedbcacebd
# abcdebcadaceb
# abcdecadbdace
# abcdebdcacebd
# abcdecbadaceb
# abcdeabdcebda
# abcdedacbdace
# abcdecdbacebd
# abcdebadcebda
# abcdeadcbdace
# abcdedcbacebd
# abcdeabcdbace
# abcdedabcaebd
# abcdecdabedac
# abcdebacdbace
# abcdeadbcaebd
# abcdedcabedac
# abcdebcdadceb
# abcdecabdbace
# abcdebdacaebd
# abcdecbdadceb
# abcdeacbdbace
# abcdedbacaebd
# abcdeacdbedac
# abcdedbcadceb
# abcdebcadbace
# abcdecadbedac
# abcdebdcadceb
# abcdecbadbace
# abcdeabdcaebd
# abcdedacbedac
# abcdecdbadceb
# abcdebadcaebd
# abcdeadcbedac
# abcdedcbadceb
# abcdeabcdebac
# abcdedabcdaeb
# abcdecdabceda
# abcdebacdebac
# abcdeadbcdaeb
# abcdedcabceda
# abcdebcdabdce
# abcdecabdebac
# abcdebdacdaeb
# abcdecbdabdce
# abcdeacbdebac
# abcdedbacdaeb
# abcdeacdbceda
# abcdedbcabdce
# abcdebcadebac
# abcdecadbceda
# abcdebdcabdce
# abcdecbadebac
# abcdeabdcdaeb
# abcdedacbceda
# abcdecdbabdce
# abcdebadcdaeb
# abcdeadcbceda
# abcdedcbabdce
# abcdeabcdcaeb
# abcdedabcbeda
# abcdecdabadce
# abcdebacdcaeb
# abcdeadbcbeda
# abcdedcabadce
# abcdeabcedbac
# abcdebcdaecbd
# abcdecabdcaeb
# abcdebdacbeda
# abcdebacedbac
# abcdecbdaecbd
# abcdeacbdcaeb
# abcdedbacbeda
# abcdeacdbadce
# abcdecabedbac
# abcdedbcaecbd
# abcdebcadcaeb
# abcdecadbadce
# abcdeacbedbac
# abcdebdcaecbd
# abcdecbadcaeb
# abcdeabdcbeda
# abcdedacbadce
# abcdebcaedbac
# abcdecdbaecbd
# abcdebadcbeda
# abcdeadcbadce
# abcdecbaedbac
# abcdedcbaecbd
# abcdeabcdebca
# abcdedabcdabe
# abcdecdabcead
# abcdebacdebca
# abcdeadbcdabe
# abcdedcabcead
# abcdebcdabdec
# abcdecabdebca
# abcdebdacdabe
# abcdecbdabdec
# abcdeacbdebca
# abcdedbacdabe
# abcdeacdbcead
# abcdedbcabdec
# abcdebcadebca
# abcdecadbcead
# abcdebdcabdec
# abcdecbadebca
# abcdeabdcdabe
# abcdedacbcead
# abcdecdbabdec
# abcdebadcdabe
# abcdeadcbcead
# abcdedcbabdec
# abcdeabcdcabe
# abcdedabcbead
# abcdecdabadec
# abcdebacdcabe
# abcdeadbcbead
# abcdedcabadec
# abcdeabcedbca
# abcdebcdaecdb
# abcdecabdcabe
# abcdebdacbead
# abcdebacedbca
# abcdecbdaecdb
# abcdeacbdcabe
# abcdedbacbead
# abcdeacdbadec
# abcdecabedbca
# abcdedbcaecdb
# abcdebcadcabe
# abcdecadbadec
# abcdeacbedbca
# abcdebdcaecdb
# abcdecbadcabe
# abcdeabdcbead
# abcdedacbadec
# abcdebcaedbca
# abcdecdbaecdb
# abcdebadcbead
# abcdeadcbadec
# abcdecbaedbca
# abcdedcbaecdb
# abcdeabcdabec
# abcdedabceadb
# abcdecdabdeca
# abcdebacdabec
# abcdeadbceadb
# abcdedcabdeca
# abcdebcdacdbe
# abcdecabdabec
# abcdebdaceadb
# abcdecbdacdbe
# abcdeacbdabec
# abcdedbaceadb
# abcdeacdbdeca
# abcdedbcacdbe
# abcdebcadabec
# abcdecadbdeca
# abcdebdcacdbe
# abcdecbadabec
# abcdeabdceadb
# abcdedacbdeca
# abcdecdbacdbe
# abcdebadceadb
# abcdeadcbdeca
# abcdedcbacdbe
# abcdeabcdbeca
# abcdedabcadbe
# abcdecdabecad
# abcdebacdbeca
# abcdeadbcadbe
# abcdedcabecad
# abcdebcdadbec
# abcdecabdbeca
# abcdebdacadbe
# abcdecbdadbec
# abcdeacbdbeca
# abcdedbacadbe
# abcdeacdbecad
# abcdedbcadbec
# abcdebcadbeca
# abcdecadbecad
# abcdebdcadbec
# abcdecbadbeca
# abcdeabdcadbe
# abcdedacbecad
# abcdecdbadbec
# abcdebadcadbe
# abcdeadcbecad
# abcdedcbadbec
# abcdeabcdacbe
# abcdedabcebad
# abcdecdabdaec
# abcdebacdacbe
# abcdeadbcebad
# abcdedcabdaec
# abcdebcdacedb
# abcdecabdacbe
# abcdebdacebad
# abcdecbdacedb
# abcdeacbdacbe
# abcdedbacebad
# abcdeacdbdaec
# abcdedbcacedb
# abcdebcadacbe
# abcdecadbdaec
# abcdebdcacedb
# abcdecbadacbe
# abcdeabdcebad
# abcdedacbdaec
# abcdecdbacedb
# abcdebadcebad
# abcdeadcbdaec
# abcdedcbacedb
# abcdeabcdbaec
# abcdedabcaedb
# abcdecdabedca
# abcdebacdbaec
# abcdeadbcaedb
# abcdedcabedca
# abcdebcdadcbe
# abcdecabdbaec
# abcdebdacaedb
# abcdecbdadcbe
# abcdeacbdbaec
# abcdedbacaedb
# abcdeacdbedca
# abcdedbcadcbe
# abcdebcadbaec
# abcdecadbedca
# abcdebdcadcbe
# abcdecbadbaec
# abcdeabdcaedb
# abcdedacbedca
# abcdecdbadcbe
# abcdebadcaedb
# abcdeadcbedca
# abcdedcbadcbe
# abcdeabcdeacb
# abcdedabcdeba
# abcdecdabcdae
# abcdebacdeacb
# abcdeadbcdeba
# abcdedcabcdae
# abcdebcdabced
# abcdecabdeacb
# abcdebdacdeba
# abcdecbdabced
# abcdeacbdeacb
# abcdedbacdeba
# abcdeacdbcdae
# abcdedbcabced
# abcdebcadeacb
# abcdecadbcdae
# abcdebdcabced
# abcdecbadeacb
# abcdeabdcdeba
# abcdedacbcdae
# abcdecdbabced
# abcdebadcdeba
# abcdeadcbcdae
# abcdedcbabced
# abcdeabcdceba
# abcdedabcbdae
# abcdecdabaced
# abcdebacdceba
# abcdeadbcbdae
# abcdedcabaced
# abcdeabcedacb
# abcdebcdaebdc
# abcdecabdceba
# abcdebdacbdae
# abcdebacedacb
# abcdecbdaebdc
# abcdeacbdceba
# abcdedbacbdae
# abcdeacdbaced
# abcdecabedacb
# abcdedbcaebdc
# abcdebcadceba
# abcdecadbaced
# abcdeacbedacb
# abcdebdcaebdc
# abcdecbadceba
# abcdeabdcbdae
# abcdedacbaced
# abcdebcaedacb
# abcdecdbaebdc
# abcdebadcbdae
# abcdeadcbaced
# abcdecbaedacb
# abcdedcbaebdc
# abcdeabcdbcae
# abcdedabcabed
# abcdecdabeadc
# abcdebacdbcae
# abcdeadbcabed
# abcdedcabeadc
# abcdebcdadecb
# abcdecabdbcae
# abcdebdacabed
# abcdecbdadecb
# abcdeacbdbcae
# abcdedbacabed
# abcdeacdbeadc
# abcdedbcadecb
# abcdebcadbcae
# abcdecadbeadc
# abcdebdcadecb
# abcdecbadbcae
# abcdeabdcabed
# abcdedacbeadc
# abcdecdbadecb
# abcdebadcabed
# abcdeadcbeadc
# abcdedcbadecb
# abcdeabcdaecb
# abcdedabcedba
# abcdecdabdcae
# abcdebacdaecb
# abcdeadbcedba
# abcdedcabdcae
# abcdebcdacbed
# abcdecabdaecb
# abcdebdacedba
# abcdecbdacbed
# abcdeacbdaecb
# abcdedbacedba
# abcdeacdbdcae
# abcdedbcacbed
# abcdebcadaecb
# abcdecadbdcae
# abcdebdcacbed
# abcdecbadaecb
# abcdeabdcedba
# abcdedacbdcae
# abcdecdbacbed
# abcdebadcedba
# abcdeadcbdcae
# abcdedcbacbed
# abcdeabcdecba
# abcdedabcdbae
# abcdecdabcaed
# abcdebacdecba
# abcdeadbcdbae
# abcdedcabcaed
# abcdebcdabedc
# abcdecabdecba
# abcdebdacdbae
# abcdecbdabedc
# abcdeacbdecba
# abcdedbacdbae
# abcdeacdbcaed
# abcdedbcabedc
# abcdebcadecba
# abcdecadbcaed
# abcdebdcabedc
# abcdecbadecba
# abcdeabdcdbae
# abcdedacbcaed
# abcdecdbabedc
# abcdebadcdbae
# abcdeadcbcaed
# abcdedcbabedc
# abcdeabcdcbae
# abcdedabcbaed
# abcdecdabaedc
# abcdebacdcbae
# abcdeadbcbaed
# abcdedcabaedc
# abcdeabcedcba
# abcdebcdaedcb
# abcdecabdcbae
# abcdebdacbaed
# abcdebacedcba
# abcdecbdaedcb
# abcdeacbdcbae
# abcdedbacbaed
# abcdeacdbaedc
# abcdecabedcba
# abcdedbcaedcb
# abcdebcadcbae
# abcdecadbaedc
# abcdeacbedcba
# abcdebdcaedcb
# abcdecbadcbae
# abcdeabdcbaed
# abcdedacbaedc
# abcdebcaedcba
# abcdecdbaedcb
# abcdebadcbaed
# abcdeadcbaedc
# abcdecbaedcba
# abcdedcbaedcb

printf "n=5 k=3\n"
./nnr -n 5 -l 13 | ./pes -n 5 -k 3
