#!/usr/bin/env bash

# abcdebcadbceabcd
# abcdecbadbceabcd
# abcdebcadcbeabcd
# abcdecbadcbeabcd
# abcdebcadbcedabc
# abcdecbadbcedabc
# abcdeabdcabedabc
# abcdebadcabedabc
# abcdebcadcbedabc
# abcdecbadcbedabc
# abcdeabdcbaedabc
# abcdebadcbaedabc
# abcdeabcdabecdab
# abcdebacdabecdab
# abcdeabdcabecdab
# abcdebadcabecdab
# abcdeabcdbaecdab
# abcdebacdbaecdab
# abcdeabdcbaecdab
# abcdebadcbaecdab
# abcdecabdacebacd
# abcdeacbdacebacd
# abcdecabdcaebacd
# abcdeacbdcaebacd
# abcdebcadbceadbc
# abcdecbadbceadbc
# abcdebcadcbeadbc
# abcdecbadcbeadbc
# abcdeabcdabedcab
# abcdebacdabedcab
# abcdeabdcabedcab
# abcdebadcabedcab
# abcdeabcdbaedcab
# abcdebacdbaedcab
# abcdeabdcbaedcab
# abcdebadcbaedcab
# abcdecabdacebcda
# abcdeacbdacebcda
# abcdecabdcaebcda
# abcdeacbdcaebcda
# abcdeabcdabecabd
# abcdebacdabecabd
# abcdeabcdbaecabd
# abcdebacdbaecabd
# abcdecabdacebdac
# abcdeacbdacebdac
# abcdecabdcaebdac
# abcdeacbdcaebdac
# abcdeabcdabecbda
# abcdebacdabecbda
# abcdeabcdbaecbda
# abcdebacdbaecbda
# abcdebcadbceacbd
# abcdecbadbceacbd
# abcdebcadcbeacbd
# abcdecbadcbeacbd
# abcdecabdacedbac
# abcdeacbdacedbac
# abcdeabdcabedbac
# abcdebadcabedbac
# abcdecabdcaedbac
# abcdeacbdcaedbac
# abcdeabdcbaedbac
# abcdebadcbaedbac
# abcdebcadbceacdb
# abcdecbadbceacdb
# abcdebcadcbeacdb
# abcdecbadcbeacdb
# abcdecabdacedbca
# abcdeacbdacedbca
# abcdeabdcabedbca
# abcdebadcabedbca
# abcdecabdcaedbca
# abcdeacbdcaedbca
# abcdeabdcbaedbca
# abcdebadcbaedbca
# abcdecabdacebcad
# abcdeacbdacebcad
# abcdecabdcaebcad
# abcdeacbdcaebcad
# abcdeabcdabecadb
# abcdebacdabecadb
# abcdeabcdbaecadb
# abcdebacdbaecadb
# abcdecabdacebdca
# abcdeacbdacebdca
# abcdecabdcaebdca
# abcdeacbdcaebdca
# abcdeabcdabecbad
# abcdebacdabecbad
# abcdeabcdbaecbad
# abcdebacdbaecbad
# abcdebcadbceabdc
# abcdecbadbceabdc
# abcdebcadcbeabdc
# abcdecbadcbeabdc
# abcdebcadbcedacb
# abcdecbadbcedacb
# abcdeabdcabedacb
# abcdebadcabedacb
# abcdebcadcbedacb
# abcdecbadcbedacb
# abcdeabdcbaedacb
# abcdebadcbaedacb
# abcdeabcdabecdba
# abcdebacdabecdba
# abcdeabdcabecdba
# abcdebadcabecdba
# abcdeabcdbaecdba
# abcdebacdbaecdba
# abcdeabdcbaecdba
# abcdebadcbaecdba
# abcdecabdacebadc
# abcdeacbdacebadc
# abcdecabdcaebadc
# abcdeacbdcaebadc
# abcdebcadbceadcb
# abcdecbadbceadcb
# abcdebcadcbeadcb
# abcdecbadcbeadcb
# abcdeabcdabedcba
# abcdebacdabedcba
# abcdeabdcabedcba
# abcdebadcabedcba
# abcdeabcdbaedcba
# abcdebacdbaedcba
# abcdeabdcbaedcba
# abcdebadcbaedcba

printf "n=5 k=4\n"
./nnr -n 5 -l 16 | ./pes -n 5 -k 4
